version: '3.8'

services:
  falcon-iq-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # No Mongo env needed; app reads external connection from application.properties
    environment:
      CATALINA_OPTS: >-
        -Dfile.encoding=UTF-8
        -XX:+UseG1GC
        -Xms256m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
        -Dspring.profiles.active=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
